<?php

namespace ContainerAQipjsd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSignUpTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\SignUpType' shared autowired service.
     *
     * @return \App\Form\SignUpType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/SignUpType.php';

        return $container->privates['App\\Form\\SignUpType'] = new \App\Form\SignUpType();
    }
}
