<?php

namespace ContainerEgLxmzd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KLnYWUdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KLnYWUd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KLnYWUd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manifestationRepository' => ['privates', 'App\\Repository\\ManifestationRepository', 'getManifestationRepositoryService', true],
            'request' => ['privates', '.errored..service_locator.KLnYWUd.Symfony\\Component\\BrowserKit\\Request', NULL, 'Cannot autowire service ".service_locator.KLnYWUd": it references class "Symfony\\Component\\BrowserKit\\Request" but no such service exists.'],
        ], [
            'manifestationRepository' => 'App\\Repository\\ManifestationRepository',
            'request' => 'Symfony\\Component\\BrowserKit\\Request',
        ]);
    }
}
