<?php

namespace ContainerEgLxmzd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RAuJjd1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rAuJjd1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rAuJjd1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\LieuController::manifestation' => ['privates', '.service_locator.38ucI31', 'get_ServiceLocator_38ucI31Service', true],
            'App\\Controller\\ManifestationController::afficherManifestation' => ['privates', '.service_locator.HCPWW9I', 'get_ServiceLocator_HCPWW9IService', true],
            'App\\Controller\\ManifestationController::allManifestation' => ['privates', '.service_locator.KLnYWUd', 'get_ServiceLocator_KLnYWUdService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\LieuController:manifestation' => ['privates', '.service_locator.38ucI31', 'get_ServiceLocator_38ucI31Service', true],
            'App\\Controller\\ManifestationController:afficherManifestation' => ['privates', '.service_locator.HCPWW9I', 'get_ServiceLocator_HCPWW9IService', true],
            'App\\Controller\\ManifestationController:allManifestation' => ['privates', '.service_locator.KLnYWUd', 'get_ServiceLocator_KLnYWUdService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\LieuController::manifestation' => '?',
            'App\\Controller\\ManifestationController::afficherManifestation' => '?',
            'App\\Controller\\ManifestationController::allManifestation' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\LieuController:manifestation' => '?',
            'App\\Controller\\ManifestationController:afficherManifestation' => '?',
            'App\\Controller\\ManifestationController:allManifestation' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
