<?php

namespace ContainerB4xg2HF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N_XGDzsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.N.XGDzs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.N.XGDzs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'lieuRepository' => ['privates', 'App\\Repository\\LieuRepository', 'getLieuRepositoryService', true],
            'manifestationRepository' => ['privates', 'App\\Repository\\ManifestationRepository', 'getManifestationRepositoryService', true],
        ], [
            'lieuRepository' => 'App\\Repository\\LieuRepository',
            'manifestationRepository' => 'App\\Repository\\ManifestationRepository',
        ]);
    }
}
