<?php

namespace ContainerZU4riYK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HCPWW9IService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HCPWW9I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HCPWW9I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manifestationRepository' => ['privates', 'App\\Repository\\ManifestationRepository', 'getManifestationRepositoryService', true],
        ], [
            'manifestationRepository' => 'App\\Repository\\ManifestationRepository',
        ]);
    }
}
