<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFGrCCQo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFGrCCQo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFGrCCQo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFGrCCQo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFGrCCQo\App_KernelDevDebugContainer([
    'container.build_hash' => 'FGrCCQo',
    'container.build_id' => 'b3323072',
    'container.build_time' => 1669665523,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFGrCCQo');
