<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA0g9iRX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA0g9iRX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA0g9iRX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA0g9iRX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA0g9iRX\App_KernelDevDebugContainer([
    'container.build_hash' => 'A0g9iRX',
    'container.build_id' => '42c46a09',
    'container.build_time' => 1669477798,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA0g9iRX');
