<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8BI7PBL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8BI7PBL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8BI7PBL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8BI7PBL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8BI7PBL\App_KernelDevDebugContainer([
    'container.build_hash' => '8BI7PBL',
    'container.build_id' => 'fd43998f',
    'container.build_time' => 1669579653,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8BI7PBL');
